apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx.configuration
data:
  default.conf: |
    server {
        listen        *:80;
        location / {
            proxy_pass http://127.0.0.1:80;
        }
    }
  