apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: jenkins/jenkins:lts
        ports:
        - containerPort: 8080
          name: jenkins
        env:
          - name: JAVA_OPTS
            value: "-Djenkins.install.runSetupWizard=false"
